-- StockSense - Inventory Management System
-- PostgreSQL schema (safe to run multiple times).

-- ---------------------------------------------------------------------------
-- Users & authentication
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name           VARCHAR(100) NOT NULL,
  email          VARCHAR(255) NOT NULL UNIQUE,            -- stored lowercase
  password_hash  TEXT NOT NULL,
  role           VARCHAR(20) NOT NULL DEFAULT 'staff' CHECK (role IN ('manager', 'staff')),
  token_version  INTEGER NOT NULL DEFAULT 0,              -- bumped on logout / password reset
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS password_reset_otps (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  otp_hash    TEXT NOT NULL,
  expires_at  TIMESTAMPTZ NOT NULL,
  attempts    INTEGER NOT NULL DEFAULT 0,
  used_at     TIMESTAMPTZ,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS password_reset_otps_user_idx ON password_reset_otps (user_id, created_at DESC);

-- ---------------------------------------------------------------------------
-- Warehouses & locations (multi-warehouse support)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS warehouses (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        VARCHAR(100) NOT NULL,
  code        VARCHAR(10) NOT NULL UNIQUE,                -- short code used in references, e.g. WH
  address     TEXT,
  is_active   BOOLEAN NOT NULL DEFAULT TRUE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS locations (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  warehouse_id  INTEGER NOT NULL REFERENCES warehouses(id) ON DELETE RESTRICT,
  name          VARCHAR(100) NOT NULL,                    -- e.g. Rack A, Production Floor
  code          VARCHAR(20) NOT NULL,                     -- e.g. RACK-A (full code: WH/RACK-A)
  is_active     BOOLEAN NOT NULL DEFAULT TRUE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (warehouse_id, code)
);

-- ---------------------------------------------------------------------------
-- Products
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS categories (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         VARCHAR(100) NOT NULL UNIQUE,
  description  TEXT,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS products (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         VARCHAR(150) NOT NULL,
  sku          VARCHAR(50) NOT NULL UNIQUE,
  category_id  INTEGER REFERENCES categories(id) ON DELETE SET NULL,
  uom          VARCHAR(20) NOT NULL DEFAULT 'Units',      -- unit of measure: Units, kg, m, L ...
  cost_price   NUMERIC(12, 2) NOT NULL DEFAULT 0 CHECK (cost_price >= 0),
  description  TEXT,
  is_active    BOOLEAN NOT NULL DEFAULT TRUE,             -- archived products are hidden, history is kept
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS products_category_idx ON products (category_id);

-- Current stock of each product in each location.
CREATE TABLE IF NOT EXISTS stock_quants (
  product_id   INTEGER NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
  location_id  INTEGER NOT NULL REFERENCES locations(id) ON DELETE RESTRICT,
  quantity     NUMERIC(14, 3) NOT NULL DEFAULT 0 CHECK (quantity >= 0),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (product_id, location_id)
);
CREATE INDEX IF NOT EXISTS stock_quants_location_idx ON stock_quants (location_id);

-- Reordering rules: alert when stock in a warehouse drops to min_qty, refill up to max_qty.
CREATE TABLE IF NOT EXISTS reorder_rules (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id    INTEGER NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  warehouse_id  INTEGER NOT NULL REFERENCES warehouses(id) ON DELETE CASCADE,
  min_qty       NUMERIC(14, 3) NOT NULL CHECK (min_qty >= 0),
  max_qty       NUMERIC(14, 3) NOT NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (product_id, warehouse_id),
  CHECK (max_qty >= min_qty)
);

-- ---------------------------------------------------------------------------
-- Operations: receipts, delivery orders, internal transfers, adjustments
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS operations (
  id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reference           VARCHAR(30) NOT NULL UNIQUE,        -- WH/IN/0001, WH/OUT/0001, WH/INT/0001, WH/ADJ/0001
  type                VARCHAR(20) NOT NULL CHECK (type IN ('receipt', 'delivery', 'internal', 'adjustment')),
  status              VARCHAR(20) NOT NULL DEFAULT 'draft'
                        CHECK (status IN ('draft', 'waiting', 'ready', 'done', 'canceled')),
  warehouse_id        INTEGER NOT NULL REFERENCES warehouses(id),
  source_location_id  INTEGER REFERENCES locations(id),   -- NULL for receipts (goods come from a vendor)
  dest_location_id    INTEGER REFERENCES locations(id),   -- NULL for deliveries (goods go to a customer)
  partner_name        VARCHAR(150),                       -- supplier (receipt) / customer (delivery)
  scheduled_date      TIMESTAMPTZ NOT NULL DEFAULT now(),
  responsible_id      INTEGER REFERENCES users(id) ON DELETE SET NULL,
  notes               TEXT,
  picked_at           TIMESTAMPTZ,                        -- delivery: pick step
  packed_at           TIMESTAMPTZ,                        -- delivery: pack step
  done_at             TIMESTAMPTZ,
  created_by          INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (
    (type = 'receipt'    AND source_location_id IS NULL AND dest_location_id IS NOT NULL) OR
    (type = 'delivery'   AND source_location_id IS NOT NULL AND dest_location_id IS NULL) OR
    (type = 'internal'   AND source_location_id IS NOT NULL AND dest_location_id IS NOT NULL
                         AND source_location_id <> dest_location_id) OR
    (type = 'adjustment' AND source_location_id IS NOT NULL AND source_location_id = dest_location_id)
  )
);
CREATE INDEX IF NOT EXISTS operations_type_status_idx ON operations (type, status);
CREATE INDEX IF NOT EXISTS operations_warehouse_idx ON operations (warehouse_id);
CREATE INDEX IF NOT EXISTS operations_scheduled_idx ON operations (scheduled_date);

CREATE TABLE IF NOT EXISTS operation_lines (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  operation_id     INTEGER NOT NULL REFERENCES operations(id) ON DELETE CASCADE,
  product_id       INTEGER NOT NULL REFERENCES products(id),
  quantity         NUMERIC(14, 3) NOT NULL CHECK (quantity >= 0), -- demand; for adjustments the counted qty
  system_quantity  NUMERIC(14, 3),                                -- adjustments: recorded qty before the count
  UNIQUE (operation_id, product_id)
);
CREATE INDEX IF NOT EXISTS operation_lines_product_idx ON operation_lines (product_id);

-- ---------------------------------------------------------------------------
-- Stock ledger: every stock change is logged here (move history)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS stock_moves (
  id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  operation_id      INTEGER REFERENCES operations(id) ON DELETE SET NULL,
  reference         VARCHAR(30) NOT NULL,
  move_type         VARCHAR(20) NOT NULL CHECK (move_type IN ('receipt', 'delivery', 'internal', 'adjustment')),
  product_id        INTEGER NOT NULL REFERENCES products(id),
  from_location_id  INTEGER REFERENCES locations(id),     -- NULL = outside (vendor / adjustment gain)
  to_location_id    INTEGER REFERENCES locations(id),     -- NULL = outside (customer / adjustment loss)
  quantity          NUMERIC(14, 3) NOT NULL CHECK (quantity > 0),
  partner_name      VARCHAR(150),
  created_by        INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (from_location_id IS NOT NULL OR to_location_id IS NOT NULL)
);
CREATE INDEX IF NOT EXISTS stock_moves_product_idx ON stock_moves (product_id, created_at DESC);
CREATE INDEX IF NOT EXISTS stock_moves_created_idx ON stock_moves (created_at DESC);
CREATE INDEX IF NOT EXISTS stock_moves_from_idx ON stock_moves (from_location_id);
CREATE INDEX IF NOT EXISTS stock_moves_to_idx ON stock_moves (to_location_id);

-- Per-prefix counters for operation references (WH/IN -> 1, 2, 3 ...).
CREATE TABLE IF NOT EXISTS sequences (
  key         VARCHAR(50) PRIMARY KEY,
  last_value  INTEGER NOT NULL
);
