-- StockSense Inventory Management System
-- Database Schema

CREATE TABLE IF NOT EXISTS users (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name           VARCHAR(100) NOT NULL,
  email          VARCHAR(255) NOT NULL UNIQUE,
  password_hash  TEXT NOT NULL,
  role           VARCHAR(20) NOT NULL DEFAULT 'staff' CHECK (role IN ('manager', 'staff')),
  token_version  INTEGER NOT NULL DEFAULT 0,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS password_reset_otps (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  otp_hash    TEXT NOT NULL,
  expires_at  TIMESTAMPTZ NOT NULL,
  attempts    INTEGER NOT NULL DEFAULT 0,
  used_at     TIMESTAMPTZ,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_password_reset_otps_user ON password_reset_otps (user_id, created_at DESC);

-- Warehouses & Locations
CREATE TABLE IF NOT EXISTS warehouses (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        VARCHAR(100) NOT NULL,
  code        VARCHAR(10) NOT NULL UNIQUE,
  address     TEXT,
  is_active   BOOLEAN NOT NULL DEFAULT TRUE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS locations (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  warehouse_id  INTEGER NOT NULL REFERENCES warehouses(id) ON DELETE RESTRICT,
  name          VARCHAR(100) NOT NULL,
  code          VARCHAR(20) NOT NULL,
  is_active     BOOLEAN NOT NULL DEFAULT TRUE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (warehouse_id, code)
);

CREATE INDEX IF NOT EXISTS idx_locations_warehouse ON locations (warehouse_id);

-- Product Catalog
CREATE TABLE IF NOT EXISTS categories (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         VARCHAR(100) NOT NULL UNIQUE,
  description  TEXT,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS products (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         VARCHAR(150) NOT NULL,
  sku          VARCHAR(50) NOT NULL UNIQUE,
  category_id  INTEGER REFERENCES categories(id) ON DELETE SET NULL,
  uom          VARCHAR(20) NOT NULL DEFAULT 'Units',
  cost_price   NUMERIC(12, 2) NOT NULL DEFAULT 0 CHECK (cost_price >= 0),
  description  TEXT,
  is_active    BOOLEAN NOT NULL DEFAULT TRUE,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_products_category ON products (category_id);
CREATE INDEX IF NOT EXISTS idx_products_sku ON products (sku);

-- Stock Quants (Inventory on hand per location)
CREATE TABLE IF NOT EXISTS stock_quants (
  product_id   INTEGER NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
  location_id  INTEGER NOT NULL REFERENCES locations(id) ON DELETE RESTRICT,
  quantity     NUMERIC(14, 3) NOT NULL DEFAULT 0 CHECK (quantity >= 0),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (product_id, location_id)
);

CREATE INDEX IF NOT EXISTS idx_stock_quants_location ON stock_quants (location_id);

-- Reordering Rules (per product per warehouse)
CREATE TABLE IF NOT EXISTS reorder_rules (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id    INTEGER NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  warehouse_id  INTEGER NOT NULL REFERENCES warehouses(id) ON DELETE CASCADE,
  min_qty       NUMERIC(14, 3) NOT NULL CHECK (min_qty >= 0),
  max_qty       NUMERIC(14, 3) NOT NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (product_id, warehouse_id),
  CHECK (max_qty >= min_qty)
);

CREATE INDEX IF NOT EXISTS idx_reorder_rules_product ON reorder_rules (product_id);
CREATE INDEX IF NOT EXISTS idx_reorder_rules_warehouse ON reorder_rules (warehouse_id);

-- Operations (Receipts, Deliveries, Transfers, Adjustments)
CREATE TABLE IF NOT EXISTS operations (
  id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reference           VARCHAR(30) NOT NULL UNIQUE,
  type                VARCHAR(20) NOT NULL CHECK (type IN ('receipt', 'delivery', 'internal', 'adjustment')),
  status              VARCHAR(20) NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'waiting', 'ready', 'done', 'canceled')),
  warehouse_id        INTEGER NOT NULL REFERENCES warehouses(id),
  source_location_id  INTEGER REFERENCES locations(id),
  dest_location_id    INTEGER REFERENCES locations(id),
  partner_name        VARCHAR(150),
  scheduled_date      TIMESTAMPTZ NOT NULL DEFAULT now(),
  responsible_id      INTEGER REFERENCES users(id) ON DELETE SET NULL,
  notes               TEXT,
  picked_at           TIMESTAMPTZ,
  packed_at           TIMESTAMPTZ,
  done_at             TIMESTAMPTZ,
  created_by          INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (
    (type = 'receipt'    AND source_location_id IS NULL AND dest_location_id IS NOT NULL) OR
    (type = 'delivery'   AND source_location_id IS NOT NULL AND dest_location_id IS NULL) OR
    (type = 'internal'   AND source_location_id IS NOT NULL AND dest_location_id IS NOT NULL AND source_location_id <> dest_location_id) OR
    (type = 'adjustment' AND source_location_id IS NOT NULL AND source_location_id = dest_location_id)
  )
);

CREATE INDEX IF NOT EXISTS idx_operations_type_status ON operations (type, status);
CREATE INDEX IF NOT EXISTS idx_operations_warehouse ON operations (warehouse_id);
CREATE INDEX IF NOT EXISTS idx_operations_scheduled ON operations (scheduled_date);
CREATE INDEX IF NOT EXISTS idx_operations_reference ON operations (reference);

CREATE TABLE IF NOT EXISTS operation_lines (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  operation_id     INTEGER NOT NULL REFERENCES operations(id) ON DELETE CASCADE,
  product_id       INTEGER NOT NULL REFERENCES products(id),
  quantity         NUMERIC(14, 3) NOT NULL CHECK (quantity >= 0),
  system_quantity  NUMERIC(14, 3),
  UNIQUE (operation_id, product_id)
);

CREATE INDEX IF NOT EXISTS idx_operation_lines_product ON operation_lines (product_id);
CREATE INDEX IF NOT EXISTS idx_operation_lines_op ON operation_lines (operation_id);

-- Stock Move Ledger
CREATE TABLE IF NOT EXISTS stock_moves (
  id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  operation_id      INTEGER REFERENCES operations(id) ON DELETE SET NULL,
  reference         VARCHAR(30) NOT NULL,
  move_type         VARCHAR(20) NOT NULL CHECK (move_type IN ('receipt', 'delivery', 'internal', 'adjustment')),
  product_id        INTEGER NOT NULL REFERENCES products(id),
  from_location_id  INTEGER REFERENCES locations(id),
  to_location_id    INTEGER REFERENCES locations(id),
  quantity          NUMERIC(14, 3) NOT NULL CHECK (quantity > 0),
  partner_name      VARCHAR(150),
  created_by        INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (from_location_id IS NOT NULL OR to_location_id IS NOT NULL)
);

CREATE INDEX IF NOT EXISTS idx_stock_moves_product ON stock_moves (product_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_stock_moves_created ON stock_moves (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_stock_moves_from ON stock_moves (from_location_id);
CREATE INDEX IF NOT EXISTS idx_stock_moves_to ON stock_moves (to_location_id);

-- Reference numbering sequences
CREATE TABLE IF NOT EXISTS sequences (
  key         VARCHAR(50) PRIMARY KEY,
  last_value  INTEGER NOT NULL
);

INSERT INTO sequences (key, last_value) VALUES
  ('WH/IN', 0),
  ('WH/OUT', 0),
  ('WH/INT', 0),
  ('WH/ADJ', 0)
ON CONFLICT (key) DO NOTHING;
